name: trocbuy
description: Application de petites annonces.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.8+37

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  #google_mobile_ads: ^2.4.0
  app_settings: ^4.1.8
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.3.1
  contained_tab_bar_view: ^0.8.0
  cupertino_icons: ^1.0.2
  date_time_format: ^2.0.1
  diacritic: ^0.1.3
  easy_splash_screen: ^1.0.3
  extended_image: ^6.2.1
  firebase_auth: ^4.2.5
  firebase_core: ^2.9.0
  firebase_storage: ^11.0.10
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_email_sender: ^5.1.0
  flutter_typeahead: ^4.3.1
  fluttertoast: ^8.0.9
  google_maps_flutter: ^2.2.3
  google_sign_in: ^5.4.0
  http: ^0.13.5
  http_auth: ^1.0.1
  image_picker: ^0.8.5+3
  json_annotation: ^4.6.0
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  path_provider: ^2.0.11
  progress_indicators: ^1.0.0
  provider: ^6.0.3
  #r_get_ip: ^0.1.1
  ribbon_widget: ^1.0.5
  share: ^2.0.4
  shared_preferences: ^2.1.0
  smooth_star_rating_null_safety: ^1.0.4+2
  sqflite: ^2.0.3
  sticky_headers: ^0.3.0+2
  url_launcher: ^6.1.5
  webview_flutter: ^3.0.4
  admob_flutter: ^3.0.0
  email_validator: ^2.1.17
  intl_phone_number_input: ^0.7.3+1
  new_version_plus: ^0.0.9
  intl: ^0.17.0
  flutter_local_notifications: ^14.0.0+1
  audioplayers: ^4.0.1
  rx_shared_preferences: ^3.0.0





dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0


flutter:
  uses-material-design: true

  assets:
    - images/
    - images/cat_lang/

  fonts:
    - family: twc
      fonts:
        - asset: fonts/twcencondensed.TTF
          weight: 700
    - family: ytv
      fonts:
        - asset: fonts/Yantramanav.ttf
          weight: 700
