enum FilterNames {
  premiumSingleCat,
  premium,
  newAds,
  allAds,
  singleAdImages,
  singleAd,
  features,
  options,
  adsOfAdvertiser,
  filterByCategory,
  filterByRegion,
  filterByCounty,
  getCatLang,
  getSubCatLang,
  getQuantityCatLang, searchResult,
  countAuthorAds,
  countCountyAds,
  countRegionAds,
  countAllFranceAds,
  aroundMe,
  countAroundMeAds,
  getCatLangFromIdCat
}
